apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec: 
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "mustafa.mirreh10@gmail.com"
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z02400013U7K3OO6ZCCK8
          region: eu-west-2
      selector:
        dnsZones:
        - "labs.mustafamirreh.com"
    - http01:
        ingress:
          class: nginx    

