apiVersion: v1
kind: Service
metadata:
  name: threat-composer
  labels:
    app: threat-composer
spec:
  selector:
    app: threat-composer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
