name: Destroy Infrastructure and Uninstall Helm Charts

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm destruction and uninstallation'
        required: true
        default: 'no'

jobs:
  cleanup-and-destroy:
    name: Uninstall Helm Charts and Destroy Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig --region eu-west-2 --name eks-cluster

    - name: Uninstall Helm Charts
      run: |
        helm uninstall nginx-ingress -n nginx-ingress || true
        helm uninstall cert-manager -n cert-manager || true
        helm uninstall external-dns -n external-dns || true
        helm uninstall argocd -n argocd || true
        helm uninstall prometheus -n prometheus || true
        helm uninstall grafana -n grafana || true
        helm uninstall threat-composer -n threat-namespace || true

    - name: Delete Namespaces
      run: |
        kubectl delete namespace nginx-ingress --ignore-not-found
        kubectl delete namespace cert-manager --ignore-not-found
        kubectl delete namespace external-dns --ignore-not-found
        kubectl delete namespace argocd --ignore-not-found
        kubectl delete namespace prometheus --ignore-not-found
        kubectl delete namespace grafana --ignore-not-found
        kubectl delete namespace threat-namespace --ignore-not-found

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Destroy
      working-directory: terraform
      run: terraform destroy --auto-approve
